version: '3'

services:
  dante:
    build: './'
    image: makeomatic/dante
    ports:
      - "9849:1080"
    volumes:
      - ./root/etc/sockd.conf:/etc/sockd.conf
    environment:
      - SOCKS_USERNAME=${SOCKS_USERNAME}
      - SOCKS_PASSWORD=${SOCKS_PASSWORD}
      - WORKERS=${WORKERS:-10}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
