version: '3'

services:
  dante:
    build: './'
    network_mode: host
    image: makeomatic/dante
    ports:
      - "1080:1080"
    environment:
      - SOCKS_USERNAME=${SOCKS_USERNAME}
      - SOCKS_PASSWORD=${SOCKS_PASSWORD}
      - WORKERS=${WORKERS:-10}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
