version: '2.4'

networks:
  app_net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1

services:
  dante:
    build: './'
    image: makeomatic/dante
    networks:
      app_net:
    ports:
      - "1080:1080"
      - "4024-4048:4024-4048/udp"
    volumes:
      - ./configs/1080.conf:/etc/sockd.conf
    environment:
      - SOCKS_USERNAME=${SOCKS_USERNAME}
      - SOCKS_PASSWORD=${SOCKS_PASSWORD}
      - WORKERS=${WORKERS:-20}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"

  dante_2:
    build: './'
    image: makeomatic/dante
    networks:
      app_net:
    ports:
      - "9080:9080"
      - "4049-4073:4049-4073/udp"
    volumes:
      - ./configs/9080.conf:/etc/sockd.conf
    environment:
      - SOCKS_USERNAME=${SOCKS_USERNAME}
      - SOCKS_PASSWORD=${SOCKS_PASSWORD}
      - WORKERS=${WORKERS:-20}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
